red = int(input('Введіть червону складову кольору RGB (від 0 до 255 включно): '))
green = int(input('Введіть зелену складову кольору RGB (від 0 до 255 включно): '))
blue = int(input('Введіть синю складову кольору RGB (від 0 до 255 включно): '))
tuple_rgb = (red, green, blue)
print(f'RGB колір - {tuple_rgb}')